// Serves the screen-reader harness. See README.md.
//
// A plain node server rather than Vite, for the same reason svg-injector's
// manual checks use one: the responses have to be genuine. The control case
// needs a real slow response, and the cached cases need the browser's own
// caching and svg-injector's cache to behave as they would in production.
//
//   npm run build
//   node test/manual/server.mjs
//
// Everything the page loads comes out of the working tree: react-svg from
// dist/, and svg-injector and React from node_modules/. Nothing is fetched
// from a CDN, so the harness runs offline and always against the versions
// package.json pins.

import { createReadStream } from 'node:fs'
import { readFile, stat } from 'node:fs/promises'
import { createServer } from 'node:http'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const require = createRequire(import.meta.url)
const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(here, '..', '..')
// Not 4190: that is ManageSieve, which sits on the Fetch standard's blocked
// port list. WebKit enforces it by refusing to open a socket at all, so Safari
// lands on about:blank with nothing reaching the server, while Chromium loads
// the page and hides the problem.
const port = 4191

// The two ES modules the page imports by bare specifier. dist/ so the harness
// tests the build being released, and node_modules/ so svg-injector is exactly
// the version package.json pins.
const vendored = {
  'react-svg.mjs': join(repoRoot, 'dist', 'react-svg.mjs'),
  'react-svg.mjs.map': join(repoRoot, 'dist', 'react-svg.mjs.map'),
  'svg-injector.mjs': join(
    repoRoot,
    'node_modules',
    '@tanem',
    'svg-injector',
    'dist',
    'svg-injector.mjs',
  ),
  'svg-injector.mjs.map': join(
    repoRoot,
    'node_modules',
    '@tanem',
    'svg-injector',
    'dist',
    'svg-injector.mjs.map',
  ),
}

// React ships no ES module build, so it cannot be imported by a browser the
// way the two above are. Rather than fetch an ESM-converted copy from a CDN,
// which needs network and pins a second React version alongside the one in
// package.json, the page loads these CJS files as classic scripts under the
// wrapper below.
//
// Listed in dependency order, which is the order index.html loads them in:
// each one requires only the ones before it. The development builds, because
// their warnings are worth having in a hand-run harness.
const reactCjs = {
  react: ['react', 'cjs/react.development.js'],
  scheduler: ['scheduler', 'cjs/scheduler.development.js'],
  'react-dom': ['react-dom', 'cjs/react-dom.development.js'],
  'react-dom/client': ['react-dom', 'cjs/react-dom-client.development.js'],
}

// Located through each package's `package.json`, which every exports map
// exposes, rather than by resolving the CJS file directly: React's exports map
// does not list `./cjs/*`, so asking node for it throws.
const cjsPath = ([packageName, file]) =>
  join(dirname(require.resolve(`${packageName}/package.json`)), file)

// Each CJS file, wrapped so it runs in a browser: a `module`/`exports` pair to
// assign to, a `require` reading back what the earlier scripts registered, and
// a `process` for React's `NODE_ENV` checks. All four are declared inside the
// function, so nothing lands on `window` except the registry.
const wrapCjs = (name, source) => `;(function () {
  globalThis.__cjs = globalThis.__cjs ?? {}
  const module = { exports: {} }
  const exports = module.exports
  const process = { env: { NODE_ENV: 'development' } }
  const require = (id) => {
    if (!(id in globalThis.__cjs)) {
      throw new Error(
        \`the harness CJS loader has no "\${id}"; check the script order in index.html\`,
      )
    }
    return globalThis.__cjs[id]
  }
${source}
  globalThis.__cjs[${JSON.stringify(name)}] = module.exports
})()
`

// The ES module the import map points `react` and `react-dom/client` at. Its
// named exports are read off the real module as it is served rather than
// listed here, so a React upgrade that adds one needs no edit.
//
// The named exports are what `import * as React from 'react'` in
// dist/react-svg.mjs needs; a default-only shim would hand it an empty
// namespace.
const shimEsm = (name) => {
  const names = Object.keys(require(name)).filter((key) =>
    /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key),
  )
  return `// Generated by test/manual/server.mjs from the CJS ${name} that index.html loads.
const loaded = globalThis.__cjs[${JSON.stringify(name)}]
if (!loaded) {
  throw new Error(
    '${name} is not loaded; index.html has to run the CJS scripts before any module',
  )
}
export default loaded
export const { ${names.join(', ')} } = loaded
`
}

const icon = (
  label,
  hue,
) => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" width="48" height="48">
  <circle cx="24" cy="24" r="22" fill="hsl(${hue} 70% 55%)" />
  <text x="24" y="31" font-family="sans-serif" font-size="20" font-weight="700" fill="#fff" text-anchor="middle">${label}</text>
</svg>
`

// Request counter. A cached remount that quietly refetched would still look
// right on screen, so the harness reads this before and after each case and
// reports the delta.
const hits = new Map()
const countHit = (path) => {
  hits.set(path, (hits.get(path) ?? 0) + 1)
}

const sleep = (ms) =>
  new Promise((resolve) => {
    setTimeout(resolve, ms)
  })

const sendJavaScript = (res, source) => {
  res.writeHead(200, {
    'Cache-Control': 'no-store',
    'Content-Type': 'text/javascript; charset=utf-8',
  })
  res.end(source)
}

const sendFile = async (res, path, contentType) => {
  try {
    await stat(path)
  } catch {
    res.writeHead(404, { 'Content-Type': 'text/plain' })
    res.end(`Not built: ${path}\n\nRun \`npm run build\` in the repo root.`)
    return
  }
  res.writeHead(200, {
    'Cache-Control': 'no-store',
    'Content-Type': contentType,
  })
  createReadStream(path).pipe(res)
}

const handle = async (req, res) => {
  const url = new URL(req.url, `http://localhost:${port}`)
  const path = url.pathname

  // Access log. A browser showing a blank page is ambiguous until you know
  // whether it asked for anything, so the harness says what it was asked for.
  res.on('finish', () => {
    console.log(`${res.statusCode} ${req.method} ${req.url}`)
  })

  if (path === '/' || path === '/index.html') {
    await sendFile(res, join(here, 'index.html'), 'text/html; charset=utf-8')
    return
  }

  if (path === '/app.mjs') {
    await sendFile(res, join(here, 'app.mjs'), 'text/javascript; charset=utf-8')
    return
  }

  const cjsMatch = path.match(/^\/vendor\/cjs\/(.+)\.js$/)
  if (cjsMatch && reactCjs[cjsMatch[1]]) {
    const name = cjsMatch[1]
    sendJavaScript(
      res,
      wrapCjs(name, await readFile(cjsPath(reactCjs[name]), 'utf8')),
    )
    return
  }

  const shimMatch = path.match(/^\/vendor\/(react|react-dom\/client)\.mjs$/)
  if (shimMatch) {
    sendJavaScript(res, shimEsm(shimMatch[1]))
    return
  }

  const vendorMatch = path.match(/^\/vendor\/(.+)$/)
  if (vendorMatch && vendored[vendorMatch[1]]) {
    const contentType = vendorMatch[1].endsWith('.map')
      ? 'application/json; charset=utf-8'
      : 'text/javascript; charset=utf-8'
    await sendFile(res, vendored[vendorMatch[1]], contentType)
    return
  }

  if (path === '/hits') {
    res.writeHead(200, {
      'Cache-Control': 'no-store',
      'Content-Type': 'application/json',
    })
    res.end(
      JSON.stringify({
        hits: Object.fromEntries(hits),
        total: [...hits.values()].reduce((a, b) => a + b, 0),
      }),
    )
    return
  }

  // Cached-case icons. Each index is a distinct URL, so svg-injector caches
  // them separately and a remount of the same index is a cache hit.
  const iconMatch = path.match(/^\/icons\/(\d+)\.svg$/)
  if (iconMatch) {
    const index = Number(iconMatch[1])
    countHit(path)
    res.writeHead(200, {
      // The browser cache must not stand in for svg-injector's. Only the
      // second injection of a given index should be free of a request, and
      // that has to be svg-injector's doing.
      'Cache-Control': 'no-store',
      'Content-Type': 'image/svg+xml',
    })
    res.end(icon(String(index), (index * 47) % 360))
    return
  }

  // Control case. `n` busts svg-injector's cache so every run is a cold load,
  // and `ms` holds the response open long enough that the loading element is
  // unambiguously present for a human-observable stretch.
  if (path === '/slow.svg') {
    countHit(path)
    const ms = Number(url.searchParams.get('ms') ?? 2500)
    await sleep(ms)
    res.writeHead(200, {
      'Cache-Control': 'no-store',
      'Content-Type': 'image/svg+xml',
    })
    res.end(icon('S', 200))
    return
  }

  res.writeHead(404, { 'Content-Type': 'text/plain' })
  res.end('Not found')
}

// A rejection inside the handler would otherwise take the process down with
// it, which in a hand-run harness costs the whole run rather than one
// response. Report it on the failing request instead, and keep serving.
const server = createServer((req, res) => {
  handle(req, res).catch((error) => {
    console.log(`-- ${req.url} failed: ${error.stack}`)
    res.writeHead(500, { 'Content-Type': 'text/plain' })
    res.end(String(error.stack))
  })
})

// Connection-level logging, one level below the access log. A browser that
// silently upgraded to https opens a socket and then speaks TLS, which the
// access log cannot show because the request never parses.
server.on('connection', (socket) => {
  console.log(`-- socket from ${socket.remoteAddress}`)
})

server.on('clientError', (error, socket) => {
  console.log(
    `-- unparseable request (${error.code ?? error.message}); a TLS handshake here means the browser asked for https`,
  )
  socket.destroy()
})

server.listen(port, () => {
  console.log(`Screen-reader harness on http://localhost:${port}`)
  console.log(`Serving React ${require('react').version} from node_modules`)
  console.log('Open it with VoiceOver running and its caption panel visible.')
})
